version: '3.9'

services:
  crudservice:
    container_name: crud
    build: .
    ports:
      - "8090:8090"
      - "50051:50051"
    networks:
      - wegugin
    environment:
      - CRUD_SERVER=:8090
      - CRUD_SERVICE=:50051

networks:
  wegugin:
    external: true
   